language: node_js
node_js:
  - node
  - "iojs"
  - lts/*
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
addons:
  code_climate:
    repo_token: f65826a15e70ce17cbbe47acad87670454734f91a92cb13fca8db5c420403ecb
#after_script:
#  - npm run test:cover
#  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter