language: node_js
node_js:
  - "iojs"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
addons:
  code_climate:
    repo_token: 2d851f8f3a9348ac4f43262305037f80a730c2660fda50af8ae4d445fd89333b
after_script:
  - npm run lcov
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter